import type { Meta } from '@storybook/vue3-vite';

import { createCatalogStory } from './createCatalogStory';

const meta = {
  title: 'Core',
} satisfies Meta;

export default meta;

const createCoreStory = () => createCatalogStory('@ww/core');

export const UiAffix = createCoreStory();
export const UiScrollArea = createCoreStory();
export const UiScrollTop = createCoreStory();
export const UiAnchor = createCoreStory();
export const UiAlert = createCoreStory();
export const UiAvatar = createCoreStory();
export const UiAvatarGroup = createCoreStory();
export const UiProgress = createCoreStory();
export const UiTable = createCoreStory();
export const UiBadge = createCoreStory();
export const UiCard = createCoreStory();
export const UiDivider = createCoreStory();
export const UiSpinner = createCoreStory();
export const UiSkeleton = createCoreStory();
export const UiBreadcrumb = createCoreStory();
export const UiButton = createCoreStory();
export const UiButtonGroup = createCoreStory();
export const UiCalendar = createCoreStory();
export const UiDatePicker = createCoreStory();
export const UiDateRangePicker = createCoreStory();
export const UiTimePicker = createCoreStory();
export const UiColorPicker = createCoreStory();
export const UiFilePicker = createCoreStory();
export const UiMention = createCoreStory();
export const UiCheckbox = createCoreStory();
export const UiSwitch = createCoreStory();
export const UiCollapse = createCoreStory();
export const UiCollapsePanel = createCoreStory();
export const UiEmptyState = createCoreStory();
export const UiField = createCoreStory();
export const UiInput = createCoreStory();
export const UiTextarea = createCoreStory();
export const UiSelectSimple = createCoreStory();
export const UiGrid = createCoreStory();
export const UiSpace = createCoreStory();
export const UiFlex = createCoreStory();
export const UiIcon = createCoreStory();
export const UiWatermark = createCoreStory();
export const UiIconButton = createCoreStory();
export const UiImage = createCoreStory();
export const UiInputPassword = createCoreStory();
export const UiInputGroup = createCoreStory();
export const UiInputTag = createCoreStory();
export const UiInputOtp = createCoreStory();
export const UiMenu = createCoreStory();
export const UiSteps = createCoreStory();
export const UiNumberInput = createCoreStory();
export const UiSelect = createCoreStory();
export const UiAutocomplete = createCoreStory();
export const UiPagination = createCoreStory();
export const UiRadio = createCoreStory();
export const UiRadioGroup = createCoreStory();
export const UiRating = createCoreStory();
export const UiResult = createCoreStory();
export const UiSlider = createCoreStory();
export const UiRangeSlider = createCoreStory();
export const UiSplitter = createCoreStory();
export const UiTabsRoot = createCoreStory();
export const UiTabsList = createCoreStory();
export const UiTabsTrigger = createCoreStory();
export const UiTabsPanel = createCoreStory();
export const UiTag = createCoreStory();
export const UiTimeline = createCoreStory();
export const UiDescriptions = createCoreStory();
export const UiStatistic = createCoreStory();
export const UiList = createCoreStory();
export const UiAlertDialog = createCoreStory();
export const UiContextMenu = createCoreStory();
export const UiDialog = createCoreStory();
export const UiDrawer = createCoreStory();
export const UiDropdown = createCoreStory();
export const UiImagePreview = createCoreStory();
export const UiImagePreviewGroup = createCoreStory();
export const UiPopconfirm = createCoreStory();
export const UiPopover = createCoreStory();
export const UiToast = createCoreStory();
export const UiTooltip = createCoreStory();
