export const motionTokens = {
  motion: {
    'motion-mode': 'full',
    'motion-duration-instant': '1ms',
    'motion-duration-2xs': '90ms',
    'motion-duration-xs': '120ms',
    'motion-duration-sm': '160ms',
    'motion-duration-md': '200ms',
    'motion-duration-lg': '240ms',
    'motion-duration-xl': '320ms',
    'motion-duration-ambient-sm': '1200ms',
    'motion-duration-ambient-md': '2400ms',
    'motion-duration-ambient-lg': '3600ms',
    'motion-duration-fast': 'var(--ui-motion-duration-sm)',
    'motion-duration-medium': 'var(--ui-motion-duration-md)',
    'motion-duration-slow': 'var(--ui-motion-duration-xl)',
    'motion-easing-standard': 'cubic-bezier(0.2, 0.8, 0.2, 1)',
    'motion-easing-decelerate': 'cubic-bezier(0.16, 1, 0.3, 1)',
    'motion-easing-accelerate': 'cubic-bezier(0.4, 0, 1, 1)',
    'motion-easing-exit': 'cubic-bezier(0.7, 0, 0.84, 0)',
    'motion-easing-emphasized': 'cubic-bezier(0.22, 1, 0.36, 1)',
    'motion-easing-spring-soft': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
    'motion-easing-linear': 'linear',
    'motion-distance-2xs': '1px',
    'motion-distance-xs': '2px',
    'motion-distance-sm': '4px',
    'motion-distance-md': '8px',
    'motion-distance-lg': '12px',
    'motion-distance-xl': '16px',
    'motion-distance-2xl': '24px',
    'motion-scale-96': '0.96',
    'motion-scale-98': '0.98',
    'motion-scale-100': '1',
    'motion-scale-102': '1.02',
    'motion-scale-104': '1.04',
    'motion-opacity-0': '0',
    'motion-opacity-40': '0.4',
    'motion-opacity-56': '0.56',
    'motion-opacity-72': '0.72',
    'motion-opacity-88': '0.88',
    'motion-stagger-2xs': '16ms',
    'motion-stagger-xs': '24ms',
    'motion-stagger-sm': '32ms',
    'motion-stagger-md': '40ms',
    'motion-stagger-lg': '56ms'
  }
} as const;
