export const typographyScale = {
  typography: {
    'font-family-sans': "'Avenir Next', 'Segoe UI', sans-serif",
    'font-size-xs': '0.75rem',
    'font-size-sm': '0.875rem',
    'font-size-md': '1rem',
    'font-size-lg': '1.125rem',
    'font-size-xl': '1.25rem',
    'font-size-2xl': '1.5rem',
    'line-height-tight': '1.2',
    'line-height-body': '1.5',
    'line-height-relaxed': '1.65',
    'font-weight-regular': '400',
    'font-weight-medium': '500',
    'font-weight-semibold': '600',
    'font-weight-bold': '700',
    'letter-spacing-body': '0em',
    'letter-spacing-label': '0.04em',
    'letter-spacing-display': '-0.01em',
    'text-transform-none': 'none',
    'text-transform-label': 'uppercase',
    'font-feature-default': '"kern" 1, "liga" 1, "calt" 1',
    'font-feature-display': '"kern" 1, "liga" 1, "ss01" 1',
    'font-smoothing-webkit': 'antialiased',
    'font-smoothing-moz': 'grayscale',
  },
} as const;
